name: prime_timer
description: PrimeTimer” --org com.hmb.primeTimer”
version: 1.0.0+1
publish_to: none

environment:
  #  sdk: ">=2.17.0 <3.0.0"
  sdk: ^3.6.1
  flutter: 3.27.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  dartz: ^0.10.1
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.7.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.2

dependency_overrides:
  win32: ^5.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/0.75x/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
